### ISSUE TITLE
Internet Explorer engine not available

### ISSUE THREAD

**Issue by treyrees** [ehassett/tfvm#8]
**Describe the bug**
When installing, an Internet Explorer engine not being available prevents install.

**To Reproduce**
1. Run scoop install tfvm
2. See error

**Expected behavior**
Successful installation

**Screenshots**
![image](https://user-images.githubusercontent.com/55461896/151034747-4c3e363b-e94b-47c0-a355-e1e40ddebc22.png)

**Comment by ehassett** [comment]
This issue is not an issue with the [tfvm scoop script](bin/scoop.ps1), but rather the scoop tool itself. It can be fixed by opening IE classic and going through the security settings popup. An important thing to note is that the [tfvm scoop script](bin/scoop.ps1) only sets up the file structure in `$HOME/.tfvm` so if that script is failing, `tfvm` should still work properly.
